apply plugin: 'com.android.application'

android {
    compileSdkVersion 33

    defaultConfig {
        applicationId "com.sigma.demo"
        minSdkVersion 26
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar, "*.aar'])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

    implementation 'com.sigma.drm:sigma-player-common:2.19.1'
    implementation 'com.sigma.drm:sigma-player-container:2.19.1'
    implementation 'com.sigma.drm:sigma-player-core:2.19.1'
    implementation 'com.sigma.drm:sigma-player-extractor:2.19.1'
    implementation 'com.sigma.drm:sigma-player-dash:2.19.1'
    implementation 'com.sigma.drm:sigma-player-datasource:2.19.1'
    implementation 'com.sigma.drm:sigma-player-decoder:2.19.1'
    implementation 'com.sigma.drm:sigma-player-hls:2.19.1'
    implementation 'com.sigma.drm:sigma-player-smoothstreaming:2.19.1'
    implementation 'com.sigma.drm:sigma-player-ui:2.19.1'

    implementation 'com.google.code.gson:gson:2.8.8'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

}
